version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:22.19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run CI tests
          command: npm run test:ci

workflows:
  version: 2
  test:
    jobs:
      - test
